### ISSUE TITLE
Update substrate-node-new to use latest 1.0 tag when it is created

### ISSUE THREAD

**Issue by xlc** [paritytech/substrate-up#28]
I believe currently it is using the substrate master which is not stable
https://github.com/paritytech/substrate-up/blob/c33875f7079f13c5270664cf603ac1f3fd3d66a1/substrate-node-new#L42

When new 1.0 tag is been created, the above line should be changed to use the tagged release instead.

https://github.com/paritytech/substrate/issues/2275#issuecomment-483179984

**Comment by shawntabrizi** [comment]
A PR for this change, when ready, can be found here:
https://github.com/paritytech/substrate-up/pull/30

**Comment by gautamdhameja** [comment]
I guess this issue can be closed now as the said PR (https://github.com/paritytech/substrate-up/pull/30) is merged.
@shawntabrizi ?
