### ISSUE TITLE
Is the substrate-node-new binary update?

### ISSUE THREAD

**Issue by Lawliet-Chan** [paritytech/substrate-up#38]
Hi. 
I copy the substrate-node-new binary to my mac.(the path is ~/.cargo/bin/)
 When I used it to new a chain project and run 'cargo check', I found some error about   runtime/src/lib.rs  AS FOLLOW:

> error[E0405]: cannot find trait `AuthoritiesApi` in module `consensus_authorities`
   --> src/lib.rs:296:30
    |
296 |     impl consensus_authorities::AuthoritiesApi<Block> for Runtime {
    |                                 ^^^^^^^^^^^^^^ not found in `consensus_authorities`
help: possible candidate is found in another module, you can import it into scope
    |
   | use consensus_authorities::runtime_decl_for_AuthoritiesApi::AuthoritiesApi;
    |

error[E0425]: cannot find function `authorities_call_api_at` in module `consensus_authorities::runtime_decl_for_AuthoritiesApi`
   --> src/lib.rs:231:1
    |
 | / impl_runtime_apis! {
 | |     impl runtime_api::Core<Block> for Runtime {
 | |         fn version() -> RuntimeVersion {
 | |             VERSION
...   |
 | |     }
 | | }
    | |_^ not found in `consensus_authorities::runtime_decl_for_AuthoritiesApi`
help: possible candidate is found in another module, you can import it into scope
    |
   | use client::runtime_api::runtime_decl_for_Core::authorities_call_api_at;
    |
 error[E0425]: cannot find function `authorities_native_call_generator` in module `consensus_authorities::runtime_decl_for_AuthoritiesApi`
   --> src/lib.rs:231:1
    |
| / impl_runtime_apis! {
 | |     impl runtime_api::Core<Block> for Runtime {
 | |         fn version() -> RuntimeVersion {
 | |             VERSION
...   |
 | |     }
 | | }
    | |_^ not found in `consensus_authorities::runtime_decl_for_AuthoritiesApi`
help: possible candidate is found in another module, you can import it into scope
    |
9   | use client::runtime_api::runtime_decl_for_Core::authorities_native_call_generator;
    |
error: aborting due to 3 previous errors

Is the substrate-node-new binary update to the lastet ?

**Comment by kaichaosun** [comment]
Confirmed with @CrocdileChan, this issue is already resolved by discussing in Riot.
